Add item requests
RomanBatrakov/java-shareit pull request #3
Opened 2022-11-22 09:40 UTC by RomanBatrakov

2022-11-22 19:15 UTC, andrew-larkin requested changes
Привет! Отличный результат, качественная реализация и функционала и тестов. Остается добавить пару штрихов, в репозиториях, которые работают с Pageable, унаследоваться от PagingAndSortingRepository, кое-где добавить аннотации. Я не стал писать комменты во всех местах, но они одинаково актуальны для всех контроллеров и репозиториев.

2022-11-22 19:15 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
>  public interface BookingRepository extends JpaRepository<Booking, Integer> {
есть такой репозиторий PagingAndSortingRepository (можно унаследоваться от него) - он поддерживает Pageable, куда дополнительно можно добавить сортировку, очень рекомендую. Еще рекомендую добавить @Repository над классом

2022-11-22 19:15 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>      public ResponseEntity<List<BookingDto>> getUserBookings(@RequestHeader("X-Sharer-User-Id") int userId,
для передачи списка dto в ответ, как правило, создается еще один dto (например, BookingListDto), куда мы этот список кладем. функционал при этом не меняется, json остается таким же, но структура кода становится более "привлекательной"

2022-11-22 19:15 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemFromDb.getOwner().getId() == userId) {
может можно эту конструкцию как-нибудь упростить?

2022-11-23 05:04 UTC, RomanBatrakov commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
>  public interface BookingRepository extends JpaRepository<Booking, Integer> {
Привет! Прочитал про этот интерфейс. Да, удобно выходит, что можно сразу в Pageable сортировку вложить. В репозиториях изменил, но сами методы переписывать не стал.

2022-11-23 06:29 UTC, RomanBatrakov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemFromDb.getOwner().getId() == userId) {
Я везде старался (в меру своих способностей конечно) ) упростить код. Вот тут лучше ничего не придумал. Суть в том, чтобы заменить только ненулевые поля в объекте. Буду признателен, если даш подсказку где поискать/почитать об инструменте, чтобы это улучшить)

2022-11-23 06:32 UTC, RomanBatrakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>      public ResponseEntity<List<BookingDto>> getUserBookings(@RequestHeader("X-Sharer-User-Id") int userId,
Я попытался реализовать данную фичу и получается так, что тесты запросов падают в ошибку из-за того что ожидают список объектов, а получают один объектв котором список. Посморти пожалуйста, может я некорректно что-то реализовал?
![Снимок1](https://user-images.githubusercontent.com/102486390/203484999-cbb388bb-0455-4c21-9aa3-c05075ca8214.PNG)
![Снимок2](https://user-images.githubusercontent.com/102486390/203485002-e4960544-c5eb-4857-a621-a3eeb051014d.PNG)
![Снимок3](https://user-images.githubusercontent.com/102486390/203485004-0c3b7832-1bf4-46be-a0e4-23d1fc28f7fb.PNG)
![Снимок4](https://user-images.githubusercontent.com/102486390/203485006-3859b856-3f25-4ee5-8bc0-6cdb11615480.PNG)
![Снимок5](https://user-images.githubusercontent.com/102486390/203485007-29ec5c78-3a84-48d3-a76a-3bc9a86aefed.PNG)
![Снимок6](https://user-images.githubusercontent.com/102486390/203485008-13b79e0f-642a-4883-96e3-29d5882d38b5.PNG)

2022-11-23 07:24 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>      public ResponseEntity<List<BookingDto>> getUserBookings(@RequestHeader("X-Sharer-User-Id") int userId,
реализовано все корректно, единственное - @Component тут не обязателен, потому что это не бин. Возможно стоит немного скорректировать тест, хотя по идее json отличаться не должен

2022-11-23 07:25 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemFromDb.getOwner().getId() == userId) {
тут дело не в инструменте, а именно в бизнес-логике. возможно, существует способ сделать ее чуть легче. Если ничего не приходит в голову, то ничего страшного, это необязательное требование - больше как предложение

2022-11-23 08:02 UTC, RomanBatrakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>      public ResponseEntity<List<BookingDto>> getUserBookings(@RequestHeader("X-Sharer-User-Id") int userId,
Свои тесты я подкорректирую конечно. Тесты постмана не принимают (ссылка на которые в ТЗ дана), соответственно в гите pull request проверку тоже не пройдет.

2022-11-23 09:03 UTC, RomanBatrakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>      public ResponseEntity<List<BookingDto>> getUserBookings(@RequestHeader("X-Sharer-User-Id") int userId,
Без @component он у меня выдавал ошибку, что такого бина нет.

2022-11-23 13:53 UTC, RomanBatrakov commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemFromDb.getOwner().getId() == userId) {
Понял, исправил!

2022-11-23 20:35 UTC, merged